### ISSUE TITLE
Error: [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by spagu** [postcss/postcss-selector-not#8]
When starting app from nodejs I am getting this error:
```
/usr/local/node/CSSX/node_modules/postcss/lib/processor.js:145
        throw new Error(i + ' is not a PostCSS plugin');
        ^

Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/usr/local/node/CSSX/node_modules/postcss/lib/processor.js:145:15)
    at new Processor (/usr/local/node/CSSX/node_modules/postcss/lib/processor.js:51:25)
    at postcss (/usr/local/node/CSSX/node_modules/postcss/lib/postcss.js:73:10)
    at FileStream.<anonymous> (/usr/local/node/CSSX/ssl.js:65:1)
    at emitNone (events.js:91:20)
    at FileStream.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by Semigradsky** [comment]
Fixed in 3.0.1

**Comment by giotramu** [comment]
I have the same issue with PostCSS v8.3.6.

**Comment by carlosjeurissen** [comment]
@giotramu This can be fixed by using
`require('postcss-selector-not').default`

instead of:
`require('postcss-selector-not')`

**Comment by giotramu** [comment]
@carlosjeurissen I read about it, but I usually use the PostCSS plain configuration object in the `.postcssrc` or `.postcssrc.json` files
